# Generated by Django 5.0 on 2024-01-27 21:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_cat',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
