# Generated by Django 5.0 on 2024-01-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0002_alter_open_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_cat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
