# Generated by Django 5.0 on 2024-02-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0003_alter_open_cat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='founder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(max_length=255)),
                ('founder_image', models.ImageField(upload_to='founder/')),
                ('founder_business_type', models.CharField(max_length=255)),
                ('instagram_link', models.URLField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='president',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president_name', models.CharField(max_length=255)),
                ('president_image', models.ImageField(upload_to='president/')),
                ('president_business_type', models.CharField(max_length=255)),
                ('instagram_link', models.URLField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='secretary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretary_name', models.CharField(max_length=255)),
                ('secretary_image', models.ImageField(upload_to='secretary/')),
                ('secretary_business', models.CharField(max_length=255)),
                ('instagram_link', models.URLField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='superior_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_image', models.ImageField(upload_to='superiour_image/')),
                ('business_type', models.CharField(max_length=255)),
                ('instagram_link', models.URLField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vice_president',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vice_president_name', models.CharField(max_length=255)),
                ('vice_president_image', models.ImageField(upload_to='vice_president/')),
                ('vice_president_business_type', models.CharField(max_length=255)),
                ('instagram_link', models.URLField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=20)),
            ],
        ),
    ]
