# Generated by Django 5.0 on 2024-02-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0004_founder_president_secretary_superior_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superior_team',
            name='position',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
