# Generated by Django 5.0 on 2024-02-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0005_superior_team_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='superior_team',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
