# Generated by Django 5.0 on 2024-02-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0006_superior_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='open_cat',
            name='categorie_image',
            field=models.ImageField(default=1, upload_to='open_categories/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='open_cat',
            name='style',
            field=models.CharField(choices=[('style1', 'style1'), ('style2', 'style2'), ('style3', 'style3'), ('style4', 'style4'), ('style5', 'style5'), ('style6', 'style6')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
