# Generated by Django 5.0 on 2024-02-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0007_open_cat_categorie_image_open_cat_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='open_cat',
            name='slogans',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
