# Generated by Django 5.0 on 2024-02-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0008_open_cat_slogans'),
    ]

    operations = [
        migrations.CreateModel(
            name='coordinate_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_image', models.ImageField(upload_to='superiour_image/')),
                ('name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=255)),
                ('instagram_link', models.URLField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=250)),
            ],
        ),
    ]
