# Generated by Django 5.0 on 2024-02-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0009_coordinate_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='meeting_attenders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail', models.EmailField(max_length=200)),
                ('Name', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=1000)),
            ],
        ),
    ]
