# Generated by Django 5.0 on 2024-02-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0010_meeting_attenders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='meeting_attenders',
        ),
    ]
