# Generated by Django 5.0 on 2024-02-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0011_delete_meeting_attenders'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('services_name', models.CharField(max_length=300)),
                ('slogan', models.CharField(max_length=2000)),
            ],
        ),
    ]
