# Generated by Django 5.0 on 2024-02-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0012_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='images',
            field=models.ImageField(default=1, upload_to='service_image/'),
            preserve_default=False,
        ),
    ]
