# Generated by Django 5.0 on 2024-02-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0013_services_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='bnc_register_mem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('register_id', models.CharField(max_length=10, unique=True)),
                ('gmail', models.CharField(max_length=200)),
            ],
        ),
    ]
