# Generated by Django 5.0 on 2024-02-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0014_bnc_register_mem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnc_register_mem',
            name='register_id',
            field=models.CharField(max_length=10),
        ),
    ]
