# Generated by Django 5.0 on 2024-02-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0015_alter_bnc_register_mem_register_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnc_register_mem',
            name='gmail',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='bnc_register_mem',
            name='register_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
