# Generated by Django 5.0 on 2024-02-28 19:52

import bnc_web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0017_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.FileField(upload_to=bnc_web.models.generate_upload_path),
        ),
    ]
