# Generated by Django 5.0.2 on 2024-02-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnc_web", "0018_image_title_alter_image_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="pic",
            field=models.FileField(blank=True, upload_to="image/"),
        ),
    ]
