# Generated by Django 5.0 on 2024-02-29 20:08

import bnc_web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0019_alter_image_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('brand_name', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=50)),
                ('register_id', models.CharField(max_length=20)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.FileField(blank=True, upload_to=bnc_web.models.generate_upload_path),
        ),
    ]
