# Generated by Django 5.0.2 on 2024-03-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnc_web", "0021_userprofile_city_userprofile_company_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
