# Generated by Django 5.0.2 on 2024-03-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0023_remove_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bnc_register_mem',
            name='register_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='register_id',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
