# Generated by Django 5.0.2 on 2024-03-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0024_remove_bnc_register_mem_register_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_address',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
