# Generated by Django 5.0.2 on 2024-03-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0030_alter_userprofile_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='meeting_assign',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('meet_date', models.DateField()),
                ('meet_time', models.TimeField()),
                ('meeting_title', models.CharField(max_length=255)),
                ('meeting_content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='services',
        ),
    ]
