# Generated by Django 5.0.2 on 2024-03-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0032_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superior_team',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
