# Generated by Django 5.0.2 on 2024-03-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0033_alter_superior_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate_team',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coordinate_team',
            name='members_image',
            field=models.ImageField(upload_to='coordinate_images/'),
        ),
    ]
