# Generated by Django 5.0.2 on 2024-03-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnc_web', '0034_alter_coordinate_team_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting_assign',
            name='meeting_location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='brand_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
